name: StyleCheck

on:
  - push
  - pull_request

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet format whitespace --verify-no-changes --folder ./Assets/Scripts/*.cs
